security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: app_login_register  # La route pour afficher la page de connexion
                check_path: app_login_register  # La route où les données du formulaire de connexion sont envoyées
                default_target_path: app_homepage  # Où rediriger après connexion réussie
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: app_homepage
            # form_login:
            #     login_path: app_login
            #     check_path: app_login_check  # Remplacez "login_check" par "check_path"

            lazy: true
            provider: app_user_provider

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10